resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 6
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 4
        slowCallDurationThreshold: 3s
        slowCallRateThreshold: 50
    instances:
      products:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
    instances:
      products:
        baseConfig: default

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${IP_ADDR:http://127.0.0.1:9100}
      client:
        registration:
          client-app:
            provider: spring
            client-id: gateway-app
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8090/authorized"
            scope:
            - openid
            - profile
            client-name: client-app
        provider:
          spring:
            issuer-uri: ${IP_ADDR:http://127.0.0.1:9100}
  cloud:
    gateway:
     mvc:
      server:
        webmvc:
          routes: 

          - id: mvsc-oauth

            uri: lb://msvc-oauth

            predicates:

            - Path=/api/security/**

            filters:

            - StripPrefix=2

          - id: mvsc-users

            uri: lb://msvc-users

            predicates:

            - Path=/api/users/**

            filters:

            - StripPrefix=2

         #  - id: mvsc-products

         #    uri: lb://mvsc-products

         #    predicates:

        #     - Path=/api/products/**

            # - Header=token, 12345

            # - Method=GET, POST

            # - Query=color, verde

            # - Cookie=color, azul

            # - Header=Content-Type, application/json                

           #  filters:

            # - name: CircuitBreaker

            #   args:

            #     name: products

             #    statusCode: 500

             #    fallbackUri: forward:/api/items/5

            # - StripPrefix=2

           # - AddResponseHeader=token, abcdefg

            #- AddResponseHeader=token2, abcdefg

            #- SampleCookie=Hola mi mensaje personalizado para products

          - id: msvc-items

            uri: lb://msvc-items

            predicates:

              - Path=/api/items/**

            filters:

            - StripPrefix=2

            - AddResponseHeader=token, abcdefg

            - AddResponseHeader=token2, abcdefg

            - AddRequestHeader=token-request, 12345

            - AddResponseHeader=token-response, 54321

            - AddRequestParameter=name, Antonio

            - SetResponseHeader=Content-Type, text/plain